services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    # volumes:
    #   - pg_data:/var/lib/postgresql/data
    #   - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
    #   - ../database/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../database/seed.sql:/docker-entrypoint-initdb.d/seed.sql
      - /home/belamiqu/Matchito/database:/csv_files  # Monta el directorio local en /csv_files en el contenedor
    networks:
      matchito_network:
        aliases:
          - db

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: matchito_backend
    restart: always
    depends_on:
      - database
    ports:
      - "5000:5000"
    env_file:
      - ../.env
    volumes:
      - ../backend:/app/backend  # 🔥 Asegura que esta línea está presente
    networks:
      - matchito_network


  nginx:
    build:
      context: ..
      dockerfile: docker/Dockerfile_nginx
    container_name: matchito_nginx
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../backend/app/static:/app/backend/app/static
    networks:
      - matchito_network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - matchito_network

networks:
  matchito_network:
    driver: bridge

volumes:
  pg_data:















