# Usamos Python 3.10 como base
FROM python:3.10-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Instalar dependencias del sistema necesarias para psycopg2
RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*

# Copiar los archivos del backend dentro del contenedor
COPY . /app

# Instalar dependencias de Python
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir --force-reinstall -r requirements.txt

# Exponer el puerto en el que Flask correrá
EXPOSE 5000

# Definir variables de entorno para Flask
ENV FLASK_APP=run.py
ENV FLASK_ENV=${FLASK_ENV}
ENV PYTHONPATH=/app

# Ejecutar Flask con Python
CMD ["python", "run.py"]





