# version: "3.8"

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile_backend
    container_name: matchito_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres_db
    env_file:
      - ../.env
    volumes:
      - ../backend:/app

  postgres_db:
    image: postgres:15
    container_name: matchito_db
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../database/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  adminer:
    image: adminer
    container_name: matchito_adminer
    restart: always
    ports:
      - "8081:8080"

  nginx:
    build:
      context: ../nginx
      dockerfile: ../docker/Dockerfile_nginx
    container_name: matchito_nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata:




